# Generated by Django 2.1.5 on 2019-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
