# Generated by Django 2.1.5 on 2019-02-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='', max_length=120),
        ),
    ]
